package com.example.BusBuddy.models;

public enum TransactionType {
    TRANSACTION_TYPE_TICKET_INCOME,
    TRANSACTION_TYPE_TICKET_EXPENSE,
    TRANSACTION_TYPE_UNSPECIFIED,
    TRANSACTION_TYPE_SERVICE,
    TRANSACTION_TYPE_EMPLOYEE_SALARY
}
